// File generated by FlutterFire CLI. //flutterfire configure

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BUEJzpZ96LMsJ_RUq5zRfglUYOhovfU',
    appId: '1:28057257496:web:8fe82704aa66a8abbee56d',
    messagingSenderId: '28057257496',
    projectId: 'moviexapp-b8694',
    authDomain: 'moviexapp-b8694.firebaseapp.com',
    storageBucket: 'moviexapp-b8694.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RpzYxkkanft9yHzYqeNN-yz1i3qnh4E',
    appId: '1:28057257496:android:a41e984be4e59584bee56d',
    messagingSenderId: '28057257496',
    projectId: 'moviexapp-b8694',
    storageBucket: 'moviexapp-b8694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlqF5faJwJwKyxjwScTVnWzUBLqtByEY',
    appId: '1:28057257496:ios:62a04bebeb6d5135bee56d',
    messagingSenderId: '28057257496',
    projectId: 'moviexapp-b8694',
    storageBucket: 'moviexapp-b8694.firebasestorage.app',
    iosClientId:
        '28057257496-gg1afrovngis3trmim5ulhg155sqbjl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMoviexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLlqF5faJwJwKyxjwScTVnWzUBLqtByEY',
    appId: '1:28057257496:ios:62a04bebeb6d5135bee56d',
    messagingSenderId: '28057257496',
    projectId: 'moviexapp-b8694',
    storageBucket: 'moviexapp-b8694.firebasestorage.app',
    iosClientId:
        '28057257496-gg1afrovngis3trmim5ulhg155sqbjl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMoviexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8BUEJzpZ96LMsJ_RUq5zRfglUYOhovfU',
    appId: '1:28057257496:web:be58564689495317bee56d',
    messagingSenderId: '28057257496',
    projectId: 'moviexapp-b8694',
    authDomain: 'moviexapp-b8694.firebaseapp.com',
    storageBucket: 'moviexapp-b8694.firebasestorage.app',
  );
}
